// MEDIAS
export const GET_MEDIAS_START = "GET_MEDIAS_START";
export const GET_MEDIAS_SUCCESS = "GET_MEDIAS_SUCCESS";
export const GET_MEDIAS_FAIL = "GET_MEDIAS_FAIL";

// RATINGS
export const POST_RATING_START = "POST_RATING_START";
export const POST_RATING_SUCCESS = "POST_RATING_SUCCESS";
export const POST_RATING_FAIL = "POST_RATING_FAIL";