// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using movieAPI.Data;

namespace MovieAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211004231225_CreateMedia")]
    partial class CreateMedia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("movieAPI.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clint Eastwood"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Samuel L. Jackson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brad Pitt"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Leonardo Di Caprio"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sandra Bullock"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Robert De Niro"
                        });
                });

            modelBuilder.Entity("movieAPI.Models.ActorMedia", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.HasKey("ActorId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("ActorsMedias");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            MediaId = 1
                        },
                        new
                        {
                            ActorId = 2,
                            MediaId = 1
                        },
                        new
                        {
                            ActorId = 1,
                            MediaId = 2
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 2
                        },
                        new
                        {
                            ActorId = 2,
                            MediaId = 3
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 3
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 4
                        },
                        new
                        {
                            ActorId = 4,
                            MediaId = 4
                        },
                        new
                        {
                            ActorId = 5,
                            MediaId = 5
                        },
                        new
                        {
                            ActorId = 6,
                            MediaId = 5
                        },
                        new
                        {
                            ActorId = 6,
                            MediaId = 6
                        },
                        new
                        {
                            ActorId = 1,
                            MediaId = 6
                        },
                        new
                        {
                            ActorId = 2,
                            MediaId = 7
                        },
                        new
                        {
                            ActorId = 6,
                            MediaId = 7
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 8
                        },
                        new
                        {
                            ActorId = 4,
                            MediaId = 8
                        },
                        new
                        {
                            ActorId = 1,
                            MediaId = 9
                        },
                        new
                        {
                            ActorId = 5,
                            MediaId = 9
                        },
                        new
                        {
                            ActorId = 4,
                            MediaId = 10
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 10
                        },
                        new
                        {
                            ActorId = 5,
                            MediaId = 11
                        },
                        new
                        {
                            ActorId = 3,
                            MediaId = 11
                        },
                        new
                        {
                            ActorId = 4,
                            MediaId = 12
                        },
                        new
                        {
                            ActorId = 6,
                            MediaId = 12
                        });
                });

            modelBuilder.Entity("movieAPI.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("AvgRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgRating = 2.0,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 1"
                        },
                        new
                        {
                            Id = 2,
                            AvgRating = 4.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 2"
                        },
                        new
                        {
                            Id = 3,
                            AvgRating = 3.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2010, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 3"
                        },
                        new
                        {
                            Id = 4,
                            AvgRating = 3.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 4"
                        },
                        new
                        {
                            Id = 5,
                            AvgRating = 4.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2008, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 5"
                        },
                        new
                        {
                            Id = 6,
                            AvgRating = 1.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2001, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 6"
                        },
                        new
                        {
                            Id = 7,
                            AvgRating = 2.0,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(1994, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 7"
                        },
                        new
                        {
                            Id = 8,
                            AvgRating = 4.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(1990, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 8"
                        },
                        new
                        {
                            Id = 9,
                            AvgRating = 2.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(1978, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 9"
                        },
                        new
                        {
                            Id = 10,
                            AvgRating = 2.5,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2010, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 10"
                        },
                        new
                        {
                            Id = 11,
                            AvgRating = 4.0,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 11"
                        },
                        new
                        {
                            Id = 12,
                            AvgRating = 3.0,
                            Description = "An action movie",
                            Image = "image.jpg",
                            MediaType = 1,
                            ReleaseDate = new DateTime(2020, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Film 12"
                        });
                });

            modelBuilder.Entity("movieAPI.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MediaId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MediaId = 1,
                            Score = 3
                        },
                        new
                        {
                            Id = 2,
                            MediaId = 1,
                            Score = 1
                        },
                        new
                        {
                            Id = 3,
                            MediaId = 2,
                            Score = 4
                        },
                        new
                        {
                            Id = 4,
                            MediaId = 2,
                            Score = 5
                        },
                        new
                        {
                            Id = 5,
                            MediaId = 3,
                            Score = 5
                        },
                        new
                        {
                            Id = 6,
                            MediaId = 3,
                            Score = 2
                        },
                        new
                        {
                            Id = 7,
                            MediaId = 4,
                            Score = 3
                        },
                        new
                        {
                            Id = 8,
                            MediaId = 4,
                            Score = 4
                        },
                        new
                        {
                            Id = 9,
                            MediaId = 5,
                            Score = 4
                        },
                        new
                        {
                            Id = 10,
                            MediaId = 5,
                            Score = 5
                        },
                        new
                        {
                            Id = 11,
                            MediaId = 6,
                            Score = 1
                        },
                        new
                        {
                            Id = 12,
                            MediaId = 6,
                            Score = 2
                        },
                        new
                        {
                            Id = 13,
                            MediaId = 7,
                            Score = 3
                        },
                        new
                        {
                            Id = 14,
                            MediaId = 7,
                            Score = 1
                        },
                        new
                        {
                            Id = 15,
                            MediaId = 8,
                            Score = 4
                        },
                        new
                        {
                            Id = 16,
                            MediaId = 8,
                            Score = 5
                        },
                        new
                        {
                            Id = 17,
                            MediaId = 9,
                            Score = 3
                        },
                        new
                        {
                            Id = 18,
                            MediaId = 9,
                            Score = 2
                        },
                        new
                        {
                            Id = 19,
                            MediaId = 10,
                            Score = 1
                        },
                        new
                        {
                            Id = 20,
                            MediaId = 10,
                            Score = 4
                        },
                        new
                        {
                            Id = 21,
                            MediaId = 11,
                            Score = 3
                        },
                        new
                        {
                            Id = 22,
                            MediaId = 11,
                            Score = 5
                        },
                        new
                        {
                            Id = 23,
                            MediaId = 12,
                            Score = 5
                        },
                        new
                        {
                            Id = 24,
                            MediaId = 12,
                            Score = 1
                        });
                });

            modelBuilder.Entity("movieAPI.Models.ActorMedia", b =>
                {
                    b.HasOne("movieAPI.Models.Actor", "Actor")
                        .WithMany("ActorMedia")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("movieAPI.Models.Media", "Media")
                        .WithMany("ActorMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("movieAPI.Models.Rating", b =>
                {
                    b.HasOne("movieAPI.Models.Media", "Media")
                        .WithMany("Ratings")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("movieAPI.Models.Actor", b =>
                {
                    b.Navigation("ActorMedia");
                });

            modelBuilder.Entity("movieAPI.Models.Media", b =>
                {
                    b.Navigation("ActorMedia");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
